# jitsi-meet values

timezone: Europe/Berlin

jvb:
  auth:
    user: jvb
    password: passw0rd
  breweryMuc: jvbbrewery
 
jicofo:
  auth:
    user: focus
    password: passw0rd
  componentSecret: s3cr37

xmpp:
  server: xmpp.meet.jitsi
  domain: meet.jitsi
  authDomain: auth.meet.jitsi
  guestDomain: guest.meet.jitsi
  mucDomain: muc.meet.jitsi
  internalMucDomain: internal-muc.meet.jitsi

  jigasy:
    breweryMuc: jigasibrewery
    auth:
      user: jigasi
      password: passw0rd
