# jitsi-meet values

domains:
  - jitsi.flipnext.dev

tls:
  enabled: true
  secretName: tls-sub.flipnext.dev

timezone: Europe/Berlin


jvb:
  auth:
    user: jvb
    password: passw0rd
  breweryMuc: jvbbrewery
  udpPort: 30000
  tcpPort: 32443
  publicIP: 80.158.45.249
 
jicofo:
  auth:
    user: focus
    password: passw0rd
  componentSecret: s3cr37

xmpp:
  ports: 
    xmpp: 5222
    bosh: 5280
    components: 5347
  host: jitsi-prosody
  domain: meet.jitsi
  authDomain: auth.meet.jitsi
  guestDomain: guest.meet.jitsi
  mucDomain: muc.meet.jitsi
  internalMucDomain: internal-muc.meet.jitsi

jigasi:
  breweryMuc: jigasibrewery
  auth:
    user: jigasi
    password: passw0rd
