# jitsi-meet values

basePath: /

global:
  domains:
  - jitsi.flipnext.dev
  tls:
    enabled: true
    secretName: tls-sub.flipnext.dev

dockerTag: 3936

timezone: Europe/Berlin


jvb:
  auth:
    user: jvb
    password: passw0rd
  breweryMuc: jvbbrewery
  # make sure the public IP is the same for outward (SNAT) and inward (dnat) traffic when behind NAT
  publicIP: 80.158.20.33
  # pin the nodePort
# nodePort: 30000
  nodeSelector:
    jvb: "true"

jicofo:
  auth:
    user: focus
    password: passw0rd
  componentSecret: s3cr37

xmpp:
  ports: 
    xmpp: 5222
    bosh: 5280
    components: 5347
  host: jitsi-prosody
  domain: meet.jitsi
  authDomain: auth.meet.jitsi
  guestDomain: guest.meet.jitsi
  mucDomain: muc.meet.jitsi
  internalMucDomain: internal-muc.meet.jitsi

jigasi:
  breweryMuc: jigasibrewery
  auth:
    user: jigasi
    password: passw0rd
