# ingress templates
{{- define "jitsi.ingress" }}
kind: Ingress
apiVersion: extensions/v1beta1
{{ include "jitsi.metadata" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: nginx
    {{- if .Values.global.tls.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
spec:
{{- if .Values.global.tls.enabled }}
  tls:
  - hosts:
  {{- range .Values.global.domains }}
    - {{ . }}
  {{- end }}
    secretName: {{ .Values.global.tls.secretName }}
{{- end }}
  rules:
  {{ range .Values.global.domains -}}
  - host: {{ . }}
    http:
      paths:
{{- if eq $.Values.basePath "/" }}
      - path: /()({{ default ".*" $.path }})
{{- else }}
      - path: {{ $.Values.basePath }}(/|$)({{ default ".*" $.path }})
{{- end }}
        backend:
          serviceName: {{ $.serviceName }}
          servicePort: {{ $.servicePort }}
  {{ end }}
{{- end -}}
