# prosody
{{- $ := set . "name" "jitsi-prosody" }}

{{- $config := dict  "serviceName" $.name "servicePort" .Values.xmpp.ports.bosh "path" "http-bind" }}
{{- $config := merge $config . $config }}
{{- include "jitsi.ingress" $config }}

---
kind: Service
apiVersion: v1
{{ include "jitsi.metadata" . }}
spec:
  ports:
  - name: xmpp
    port: {{ .Values.xmpp.ports.xmpp }}
    targetPort: 5222
  - name: components
    port: {{ .Values.xmpp.ports.components }}
    targetPort: 5347
  - name: bosh
    port: {{ .Values.xmpp.ports.bosh }}
    targetPort: 5280
{{ include "jitsi.service.selector" . | indent 2 }}

---

kind: Deployment
apiVersion: extensions/v1beta1
{{ include "jitsi.metadata" . }}
spec:
  replicas: 1
  template:
{{ include "jitsi.metadata" . | indent 4 }}
    spec:
      containers:
      - name: {{ .name }}
        image: jitsi/prosody:{{ .Values.dockerTag }}
        ports:
          - containerPort: 5280
            protocol: TCP
          - containerPort: 5347
            protocol: TCP
          - containerPort: 5222
            protocol: TCP
        env:
        - name: JICOFO_AUTH_PASSWORD
          value: {{ .Values.jicofo.auth.password }}
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.auth.user }}
        - name: JICOFO_COMPONENT_SECRET
          value: {{ .Values.jicofo.componentSecret }}
        - name: JIGASI_XMPP_USER
          value: {{ .Values.jigasi.auth.user }}
        - name: JIGASI_XMPP_PASSWORD
          value: {{ .Values.jigasi.auth.passw0rd }}
        - name: JVB_AUTH_USER
          value: {{ .Values.jvb.auth.user }}
        - name: JVB_AUTH_PASSWORD
          value: {{ .Values.jvb.auth.password }}
        - name: TZ
          value: {{ .Values.timezone }}
        - name: XMPP_AUTH_DOMAIN
          value: {{ .Values.xmpp.authDomain }}
        - name: XMPP_DOMAIN
          value: {{ .Values.xmpp.domain }}
        - name: XMPP_GUEST_DOMAIN
          value: {{ .Values.xmpp.guestDomain }}
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: {{ .Values.xmpp.internalMucDomain }}
        - name: XMPP_MUC_DOMAIN
          value: {{ .Values.xmpp.mucDomain }}
        readinessProbe:
          httpGet:
            path: /http-bind
            port: 5280
        livenessProbe:
          httpGet:
            path: /http-bind
            port: 5280
