# videobridge

{{- $ := set . "name" "jitsi-videobridge" }}

kind: Service
apiVersion: v1
{{ include "jitsi.metadata" . }}
spec:
  type: NodePort 
  ports:
  - name: udp
    port: 30000
{{- if .Values.jvb.nodePort }}
    nodePort: {{ .Values.jvb.nodePort }}
{{- end }}
    protocol: UDP
{{- $ := set . "name" "jitsi-videobridge" }}
{{ include "jitsi.service.selector" . | indent 2 }}

---


kind: Deployment
apiVersion: extensions/v1beta1
{{ include "jitsi.metadata" . }}
spec:
  replicas: 1
{{ include "jitsi.deployment.selector" . | indent 2 }}
  template:
{{ include "jitsi.metadata" . | indent 4 }}
    spec:
      nodeSelector:
        {{ toYaml .Values.jvb.nodeSelector }}
      volumes:
      - name: config
        configMap:
          name: jitsi-videobridge-config
          defaultMode: 0755
      initContainers:
      - name: wait-for-prosody
        image: appropriate/curl:3.1
        command: 
        - 'sh'
        - '-c'
        - 'until curl --silent --fail ${JITSI_PROSODY_PORT_5280_TCP_ADDR}:{{ .Values.xmpp.ports.bosh }}/http-bind > /dev/null; do echo Waiting for prosody; sleep 1; done'
      containers:
      - name: {{ .name }}
        image: jitsi/jvb:{{ .Values.dockerTag }}
        volumeMounts:
        - name: config
          subPath: config
          mountPath: /etc/cont-init.d/90-k8s-config
        env:
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.auth.user }}
        - name: JVB_AUTH_USER
          value: {{ .Values.jvb.auth.user }}
        - name: JVB_AUTH_PASSWORD
          value: {{ .Values.jvb.auth.password }}
        - name: JVB_ENABLE_APIS
          value: 'rest'
        - name: JVB_BREWERY_MUC
          value: {{ .Values.jvb.breweryMuc }}
        - name: JVB_STUN_SERVERS
          value: {{ .Values.jvb.stunServers }}
        - name: JVB_TCP_HARVESTER_DISABLED
          value: "true"
        - name: JVB_PORT
          value: "30000"
        - name: TZ
          value: {{ .Values.timezone }}
        - name: XMPP_AUTH_DOMAIN
          value: {{ .Values.xmpp.authDomain }}
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: {{ .Values.xmpp.internalMucDomain }}
        - name: XMPP_SERVER
          value: {{ .Values.xmpp.host }}
        - name: LOCAL_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DOCKER_HOST_ADDRESS
          value: {{ .Values.jvb.publicIP }}
        ports:
        - containerPort: 30000
          protocol: UDP
        - containerPort: 8080
        readinessProbe:
          httpGet:
            port: 8080
            path: /about/health
        livenessProbe:
          httpGet:
            port: 8080
            path: /about/health

---

{{- $ := set . "name" "jitsi-videobridge-config" }}
apiVersion: v1
kind: ConfigMap
{{ include "jitsi.metadata" . }}
data:
  config: |-
    #!/usr/bin/with-contenv bash
    
    sed -i \
        -e 's/^\(\s*\)LOCAL_ADDRESS=.*/\1LOCAL_ADDRESS=${LOCAL_ADDRESS:?}/' \
        /etc/services.d/jvb/run
