# web 
{{- $ := set . "name" "jitsi-web" }}

{{- $config := dict  "serviceName" $.name "servicePort" 80 }}
{{- $config := merge $config . $config }}
{{- include "jitsi.ingress" $config }}
---

apiVersion: v1
kind: Service
{{ include "jitsi.metadata" . }}
spec:
  ports:
  - name: http
    port: 80
{{ include "jitsi.service.selector" . | indent 2 }}

---

apiVersion: extensions/v1beta1
kind: Deployment
{{ include "jitsi.metadata" . }}
spec:
  replicas: 1
{{ include "jitsi.deployment.selector" . | indent 2 }}
  template:
{{ include "jitsi.metadata" . | indent 4 }}
    spec:
      volumes:
      - name: config
        configMap:
          name: jitsi-web-config
          defaultMode: 0755
      containers:
      - name: {{ .name }}
        image: jitsi/web:{{ .Values.dockerTag }}
        volumeMounts:
        - name: config
          subPath: config
          mountPath: /etc/cont-init.d/90-k8s-config
        env:
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.auth.user }}
        - name: TZ
          value: {{ .Values.timezone }}
        - name: XMPP_BOSH_URL_BASE
          value: http://{{ .Values.xmpp.host }}:{{ .Values.xmpp.ports.bosh }}
        - name: XMPP_DOMAIN
          value: {{ .Values.xmpp.domain }}
        - name: XMPP_AUTH_DOMAIN
          value: {{ .Values.xmpp.authDomain }}
        - name: XMPP_GUEST_DOMAIN
          value: {{ .Values.xmpp.guestDomain }}
        - name: XMPP_MUC_DOMAIN
          value: {{ .Values.xmpp.mucDomain }}
        - name: DISABLE_HTTPS
          value: "1"
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: http
          periodSeconds: 1

---

{{- $ := set . "name" "jitsi-web-config" }}
apiVersion: v1
kind: ConfigMap
{{ include "jitsi.metadata" . }}
data:
  config: |-
    #!/usr/bin/with-contenv bash
    set -e

    # adjust config.js
    sed -i \
        -e "s/.*\(startWithVideoMuted\):.*/\1: true,/" \
        -e "s#bosh:.*#bosh: '{{ if not (eq .Values.basePath "/") }}{{ .Values.basePath }}{{ end }}/http-bind',#" \
        /config/config.js

    # fix nginx config
    cat >> /config/nginx/meet.conf << EOF

    # fix rewrite to also allow dashes in room names
    location ~ ^/([a-zA-Z0-9=\?\-]+)$ {
        rewrite ^/(.*)$ / break;
    }

    EOF

    # adjust interface_config.js
    toolbarButtons=",TOOLBAR_BUTTONS: [ 'microphone', 'camera', 'closedcaptions', 'desktop', 'fullscreen', 'fodeviceselection', 'hangup', 'profile', 'info', 'etherpad', 'settings', 'videoquality', 'filmstrip', 'feedback', 'shortcuts', 'tileview' ],"
    sed -i \
        -e "s/\(DEFAULT_BACKGROUND\):.*/\1: '#2A4B6D',/" \
        -e "s/\(INVITATION_POWERED_BY\):.*/\1: false,/" \
        -e "s/\(SHOW_JITSI_WATERMARK\):.*/\1: false,/" \
        -e "s/\(SHOW_WATERMARK_FOR_GUESTS\):.*/\1: false,/" \
        -e "s/\(DEFAULT_REMOTE_DISPLAY_NAME\):.*/\1: 'Fellow Flipster',/" \
        -e "s/\(LANG_DETECTION\):.*/\1: true,/" \
        -e "s/\(APP_NAME\):.*/\1: 'Video Conference',/" \
        -e "s/\(NATIVE_APP_NAME\):.*/\1: 'Video Conference',/" \
        -e "s/\(PROVIDER_NAME\):.*/\1: 'Flip',/" \
        -e "/^};/i $toolbarButtons" \
        /config/interface_config.js
