# jitsi config
{{- $ := set . "name" "jitsi-config" }}
apiVersion: v1
kind: ConfigMap
{{ include "jitsi.metadata" . }}
data:
  config: |-
    #!/usr/bin/with-contenv bash
    sed -i \
        -e "s/.*startWithVideoMuted:[^,]*/startWithVideoMuted: true/" \
        /config/config.js
