# jicofo
{{- $ := set . "name" "jitsi-jicofo" }}

kind: Deployment
apiVersion: extensions/v1beta1
{{ include "jitsi.metadata" . }}
metadata:
  name: jitsi-jicofo
spec:
  replicas: 1
  template:
{{ include "jitsi.metadata" . | indent 4 }}
    spec:
      containers:
      - name: {{ .name }}
        image: jitsi/jicofo
        env:
        - name: JICOFO_AUTH_PASSWORD
          value: {{ .Values.jicofo.auth.password }}
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.auth.user }}
        - name: JICOFO_COMPONENT_SECRET
          value: {{ .Values.jicofo.componentSecret }}
        - name: JIGASI_BREWERY_MUC
          value: {{ .Values.jigasi.breweryMuc }}
        - name: JVB_BREWERY_MUC
          value: {{ .Values.jvb.breweryMuc }}
        - name: TZ
          value: {{ .Values.timezone }}
        - name: XMPP_AUTH_DOMAIN
          value: {{ .Values.xmpp.authDomain }}
        - name: XMPP_DOMAIN
          value: {{ .Values.xmpp.domain }}
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: {{ .Values.xmpp.internalMucDomain }}
        - name: XMPP_SERVER
          value: {{ .Values.xmpp.server }}
