# prosody
{{- $ := set . "name" "jitsi-prosody" }}

kind: Deployment
apiVersion: extensions/v1beta1
{{ include "jitsi.metadata" . }}
spec:
  replicas: 1
  template:
{{ include "jitsi.metadata" . | indent 4 }}
    spec:
      containers:
      - name: {{ .name }}
        image: jitsi/prosody
        env:
        - name: JICOFO_AUTH_PASSWORD
          value: {{ .Values.jicofo.auth.password }}
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.auth.user }}
        - name: JICOFO_COMPONENT_SECRET
          value: {{ .Values.jicofo.component.secret }}
        - name: JIGASI_XMPP_USER
          value: {{ .Values.jigasi.auth.user }}
        - name: JIGASI_XMPP_PASSWORD
          value: {{ .Values.jigasi.auth.passw0rd }}
        - name: JVB_AUTH_USER
          value: {{ .Values.jvb.auth.user }}
        - name: JVB_AUTH_PASSWORD
          value: {{ .Values.jvb.auth.password }}
        - name: TZ
          value: {{ .Values.timezone }}
        - name: XMPP_AUTH_DOMAIN
          value: {{ .Values.xmpp.authDomain }}
        - name: XMPP_DOMAIN
          value: {{ .Values.xmpp.domain }}
        - name: XMPP_GUEST_DOMAIN
          value: {{ .Values.xmpp.guestDomain }}
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: {{ .Values.xmpp.internalMucDomain }}
        - name: XMPP_MUC_DOMAIN
          value: {{ .Values.xmpp.internalMucDomain }}
