# prosody
{{- $ := set . "name" "jitsi-prosody" }}

kind: Deployment
apiVersion: extensions/v1beta1
{{ include "jitsi.metadata" . }}
spec:
  replicas: 1
  template:
{{ include "jitsi.metadata" . | indent 4 }}
    spec:
      containers:
      - name: prosody
        image: jitsi/prosody
        env:
        - name: JICOFO_AUTH_PASSWORD
          value: passw0rd
        - name: JICOFO_AUTH_USER
          value: focus
        - name: JICOFO_COMPONENT_SECRET
          value: s3cr37
        - name: JIGASI_XMPP_PASSWORD
          value: passw0rd
        - name: JIGASI_XMPP_USER
          value: jigasi
        - name: JVB_AUTH_PASSWORD
          value: passw0rd
        - name: JVB_AUTH_USER
          value: jvb
        - name: TZ
          value: Europe/Amsterdam
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_GUEST_DOMAIN
          value: guest.meet.jitsi
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: XMPP_INTERNAL_MUC_MODULES
        - name: XMPP_MODULES
        - name: XMPP_MUC_DOMAIN
          value: muc.meet.jitsi
        - name: XMPP_MUC_MODULES
