# videobridge
{{- $ := set . "name" "jitsi-videobridge" }}

apiVersion: v1
kind: Service
{{ include "jitsi.metadata" . }}
spec:
  ports:
  - name: "10000"
    port: 10000
    protocol: UDP
    targetPort: 10000
  - name: "4443"
    port: 4443
    targetPort: 4443
{{ include "jitsi.service.selector" . | indent 2 }}

---

apiVersion: extensions/v1beta1
kind: Deployment
{{ include "jitsi.metadata" . }}
spec:
  replicas: 1
{{ include "jitsi.deployment.selector" . | indent 2 }}
  template:
{{ include "jitsi.metadata" . | indent 4 }}
    spec:
      containers:
      - name: {{ .name }}
        image: jitsi/jvb
        env:
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.auth.user }}
        - name: JVB_AUTH_USER
          value: {{ .Values.jvb.auth.user }}
        - name: JVB_AUTH_PASSWORD
          value: {{ .Values.jvb.auth.password }}
        - name: JVB_BREWERY_MUC
          value: {{ .Values.jvb.breweryMuc }}
        - name: JVB_PORT
          value: "10000"
        - name: JVB_STUN_SERVERS
          value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
        - name: JVB_TCP_HARVESTER_DISABLED
          value: "true"
        - name: JVB_TCP_PORT
          value: "4443"
        - name: TZ
          value: {{ .Values.timezone }}
        - name: XMPP_AUTH_DOMAIN
          value: {{ .Values.xmpp.authDomain }}
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: {{ .Values.xmpp.internalMucDomain }}
        - name: XMPP_SERVER
          value: {{ .Values.xmpp.server }}
        ports:
        - containerPort: 10000
          protocol: UDP
        - containerPort: 4443
