# videobridge

{{- $ := set . "name" "jitsi-videobridge-udp" }}
kind: Service
apiVersion: v1
{{ include "jitsi.metadata" . }}
spec:
  type: NodePort 
  ports:
  - name: udp
    port: {{ .Values.jvb.udpPort }}
    targetPort: {{ .Values.jvb.udpPort }}
    protocol: UDP
{{ include "jitsi.service.selector" . | indent 2 }}

---

{{- $ := set . "name" "jitsi-videobridge" }}

kind: Ingress
apiVersion: extensions/v1beta1
{{ include "jitsi.metadata" . }}
  annotations:
{{- include "jitsi.ingress.annotations" . }}
spec:
{{- if .Values.tls.enabled }}
  tls:
  - hosts:
  {{- range .Values.domains }}
    - {{ . }}
  {{- end }}
    secretName: {{ .Values.tls.secretName }}
{{- end }}
  rules:
  {{ range .Values.domains -}}
  - host: {{ . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.name }}
          servicePort: {{ $.Values.jvb.tcpPort }}
  {{ end }}

---

kind: Service
apiVersion: v1
{{ include "jitsi.metadata" . }}
spec:
  ports:
  - name: tcp
    port: {{ .Values.jvb.tcpPort }}
    targetPort: {{ .Values.jvb.tcpPort }}
{{ include "jitsi.service.selector" . | indent 2 }}

---

kind: Deployment
apiVersion: extensions/v1beta1
{{ include "jitsi.metadata" . }}
spec:
  replicas: 1
{{ include "jitsi.deployment.selector" . | indent 2 }}
  template:
{{ include "jitsi.metadata" . | indent 4 }}
    spec:
      containers:
      - name: {{ .name }}
        image: jitsi/jvb
        env:
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.auth.user }}
        - name: JVB_AUTH_USER
          value: {{ .Values.jvb.auth.user }}
        - name: JVB_AUTH_PASSWORD
          value: {{ .Values.jvb.auth.password }}
        - name: JVB_BREWERY_MUC
          value: {{ .Values.jvb.breweryMuc }}
        - name: JVB_STUN_SERVERS
          value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
        - name: JVB_TCP_HARVESTER_DISABLED
          value: "true"
        - name: JVB_PORT
          value: {{ .Values.jvb.udpPort | quote }}
        - name: JVB_TCP_PORT
          value: {{ .Values.jvb.tcpPort | quote }}
        - name: TZ
          value: {{ .Values.timezone }}
        - name: XMPP_AUTH_DOMAIN
          value: {{ .Values.xmpp.authDomain }}
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: {{ .Values.xmpp.internalMucDomain }}
        - name: XMPP_SERVER
          value: {{ .Values.xmpp.host }}
        - name: DOCKER_HOST_ADDRESS
          value: {{ .Values.jvb.publicIP }}
        ports:
        - containerPort: {{ .Values.jvb.udpPort }}
          protocol: UDP
        - containerPort: {{ .Values.jvb.tcpPort }}
