apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.fullname" . }}-web
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "jitsi-meet.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
