# web 
{{- $ := set . "name" "jitsi-web" }}

kind: Ingress
apiVersion: extensions/v1beta1
{{ include "jitsi.metadata" . }}
  annotations:
{{- include "jitsi.ingress.annotations" . }}
spec:
{{- if .Values.tls.enabled }}
  tls:
  - hosts:
  {{- range .Values.domains }}
    - {{ . }}
  {{- end }}
    secretName: {{ .Values.tls.secretName }}
{{- end }}
  rules:
  {{ range .Values.domains -}}
  - host: {{ . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.name }}
          servicePort: 80
  {{ end }}
---

apiVersion: v1
kind: Service
{{ include "jitsi.metadata" . }}
spec:
  ports:
  - name: http
    port: 80
{{ include "jitsi.service.selector" . | indent 2 }}

---

apiVersion: extensions/v1beta1
kind: Deployment
{{ include "jitsi.metadata" . }}
spec:
  replicas: 1
{{ include "jitsi.deployment.selector" . | indent 2 }}
  template:
{{ include "jitsi.metadata" . | indent 4 }}
    spec:
      volumes:
      - name: config
        configMap:
          name: jitsi-config
          defaultMode: 0755
      containers:
      - name: {{ .name }}
        image: jitsi/web
        volumeMounts:
        - name: config
          subPath: config
          mountPath: /etc/cont-init.d/90-k8s-config
        env:
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.auth.user }}
        - name: TZ
          value: {{ .Values.timezone }}
        - name: XMPP_BOSH_URL_BASE
          value: http://{{ .Values.xmpp.host }}:{{ .Values.xmpp.ports.bosh }}
        - name: XMPP_DOMAIN
          value: {{ .Values.xmpp.domain }}
        - name: XMPP_AUTH_DOMAIN
          value: {{ .Values.xmpp.authDomain }}
        - name: XMPP_GUEST_DOMAIN
          value: {{ .Values.xmpp.guestDomain }}
        - name: XMPP_MUC_DOMAIN
          value: {{ .Values.xmpp.mucDomain }}
        - name: DISABLE_HTTPS
          value: "1"
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: http
          periodSeconds: 1
